export const projects = {
    ar: [
        {
            title: "بنك بن دول للتمويل الأصغر",
            description: "صممت موقع بنك بن دول للتمويل الأصغر ليشمل مجموعة من الخدمات مثل عرض الأخبار، وتحديد مواقع الفروع وأجهزة الصراف الآلي لتسهيل الوصول إلى المعلومات المصرفية.",
            images: "bank",
            githubLink: "#",
            liveLink: "http://bindowal-001-site17.jtempurl.com/",
        },
        {
            title: "شركة بن دول للصرافة",
            description: "تم تطوير الموقع الرسمي لشركة بن دول للصرافة ليقدم معلومات شاملة عن خدمات الشركة ويعزز التواصل مع العملاء.",
            images: "exchange",
            githubLink: "#",
            liveLink: "http://bindowal-001-site17.jtempurl.com/",
        },
        {
            title: "فودستيشن",
            description: "منصة تساعد العملاء في البحث عن المطاعم القريبة، عرض القوائم، وطلب الوجبات بسهولة، تم تطويرها باستخدام ASP.NET MVC وتطبيق Flutter للهاتف.",
            images: "foodstation",
            githubLink: "https://github.com/Mohammed-k77/foodstation-platform",
            liveLink: "#",
        },
        {
            title: "نظام حماية لمراكز المجوهرات",
            description: "نظام يعمل بتقنية RFID ويقوم بإصدار تحذير عند خروج عنصر دون إذن المالك، لحماية المقتنيات الثمينة.",
            images: "protection",
            githubLink: "https://github.com/Mohammed-k77/ASM-System",
            liveLink: "#",
        },
        {
            title: "فريلانسر",
            description: "منصة تتيح تواصل أصحاب المشاريع مع المستقلين الموهوبين للعمل على المشاريع بشكل سلس واحترافي.",
            images: "freelancer",
            githubLink: "https://github.com/MohammedMazher1/Freelancer",
            liveLink: "#",
        },
        {
            title: "تستر",
            description: "منصة مخصصة للاختبارات في معسكرات التدريب، تمكن المدربين من إعداد اختبارات رقمية للطلاب قبل وبعد الدورة.",
            images: "tester",
            githubLink: "https://github.com/MohammedMazher1/Tester",
            liveLink: "#",
        },
        {
            title: "تجميع الفواتير",
            description: "تطبيق لتجميع الفواتير خاص ببنك بن داول، يساعد في إدارة الفواتير بكفاءة.",
            images: "billCollection",
            githubLink: "https://github.com/MohammedMazher1/Tester",
            liveLink: "#",
        },
    ],
    en: [
        {
            title: "Bin Dowal Microfinance Bank",
            description: "Designed the website for Bin Dowal Microfinance Bank, featuring services such as news updates, branch locations, and ATM finders to facilitate easy access to banking information.",
            images: "bank",
            githubLink: "#",
            liveLink: "http://bindowal-001-site17.jtempurl.com/",
        },
        {
            title: "Bin Dowal Exchange Company",
            description: "developed the official website for Bin Dowal Exchange, providing comprehensive information about the company’s services and facilitating customer engagement.",
            images: "exchange",
            githubLink: "#",
            liveLink: "http://bindowal-001-site17.jtempurl.com/",
        },
        {
            title: "FOODSTATION",
            description: "A food platform that allows customers to search for nearby restaurants, view menus, and place orders, developed with ASP.NET MVC and a Flutter mobile app.",
            images: "foodstation",
            githubLink: "https://github.com/Mohammed-k77/foodstation-platform",
            liveLink: "#",
        },
        {
            title: "Jewelry Protection System",
            description: "A security system using RFID to alert if any item leaves without the owner's permission, designed for jewelry centers.",
            images: "protection",
            githubLink: "https://github.com/Mohammed-k77/ASM-System",
            liveLink: "#",
        },
        {
            title: "Freelancer Platform",
            description: "A platform that connects project owners and skilled freelancers for smooth collaboration and project execution.",
            images: "freelancer",
            githubLink: "https://github.com/MohammedMazher1/Freelancer",
            liveLink: "#",
        },
        {
            title: "Tester Platform",
            description: "An innovative platform for administering tests in boot camps, allowing trainers to prepare digital pre- and post-tests.",
            images: "tester",
            githubLink: "https://github.com/MohammedMazher1/Tester",
            liveLink: "#",
        },
        {
            title: "Bill Collection App",
            description: "A bill collection app designed for Bin-Dowal Bank, streamlining the management of bills and collections.",
            images: "billCollection",
            githubLink: "https://github.com/MohammedMazher1/Tester",
            liveLink: "#",
        },
    ]
};
